- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the employee details
    ansible.builtin.debug:
      msg: "Employee is {{NAME}} and working as {{DESIGNATION}} in {{COMPANY}} "