- name: ansible conditions play with check number is less than or not
  hosts: all
  vars_prompt:
  - name: my_number
    prompt: What is your number 
    private: false
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "The given number {{ my_number }} is less than 10"
    when: my_number |int  < 10