- name: check number is less than 10 or not
  hosts: all
  vars_prompt:
  - name: my_number
    prompt: Please enter the number 
    private: false
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is less than 10"
    when: my_number  |int >= 10