- name: user creation
  hosts: localhost
  become: yes
  tasks:
  - name: check user is exists
    ansible.builtin.command: id testuser
    register: USER # Here USER is variable that outout from above ansible.builtin.command
    ignore_errors: True

  - name: create user
    ansible.builtin.command: useradd testuser
    when: USER.rc != 0  
  
  - name: print user information 
    ansible.builtin.debug:
      msg: "user info: {{ USER }}"