- name: Filter testing
  hosts: dev
  var_files:
  - vars.yaml 
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ NAME }} my designation {{ DESIGNATION }}, now I am workig {{ CGI }}""