- name: demo on filters/functions
  hosts: dev
  tasks:
  - name: print default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

  - name: convert to upper case
    vars:
      greeting: "Hello Krishna"
    ansible.builtin.debug:
      msg:  "{{ greeting | upper }}"

  - name: convert to upper case
    vars:
      greeting: "Hello Krishna"
    ansible.builtin.debug:
      msg:  "{{ greeting | lower }}"

  - name: get the unique value
    vars:
      numbers: [1,2,3,3,4,2,3,5,6,1]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"
  - name: get the unique value
    vars:
      numbers: [1,2,3,3,4,2,3,5,6,1]
    ansible.builtin.debug:
      msg: "min: {{ numbers | min }},Max: {{ numbers | max }} "
  
  - name : conver map to dictionary
    vars:
      God:
        Name: "Krishna"
        time: "Dvaparayuga"
        trainer: "Arjuna"
    ansible.builtin.debug:
      msg: "{{ God | dict2items }}"