- name: demo on filters/functions
  hosts: dev
  tasks:
  - name: print default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

  - name: convert to upper case
    vars:
      greeting: "Hello Krishna"
    ansible.builtin.debug:
      msg:  "{{ greeting | upper }}"

  - name: convert to upper case
    vars:
      greeting: "Hello Krishna"
    ansible.builtin.debug:
      msg:  "{{ greeting | lower }}"