- name: demo on fileters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"
  
  - name: Convert to uppercase
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"
  
  - name: Convert to uppercase
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

  - name: get the unique values
    vars:
      numbers: [1,2,4,5,6,2,34,5]
    ansible.builtin.debug:
      msg: {{ numbers |unique }}  